[package]
name = "permissioned-markets"
version = "0.1.0"
description = "Created with Anchor"
edition = "2024"

[lib]
crate-type = ["cdylib", "lib"]
name = "permissioned_markets"

[features]
no-entrypoint = []
no-idl = []
cpi = ["no-entrypoint"]
default = []

[dependencies]
anchor-lang = "1.1"
anchor-spl = "1.1"
serum_dex = { path = "../../../../" }
serum-dex-permissioned = { path = "../../../../permissioned" }
solana-program = "3.1.1"
